server:
  #  port: 8090
  #本机端口
  port: 8888
spring:
  application:
    name: warrenblog

  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/warrenblog
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
  security:
    salt: 'mszlu!@#'
  servlet:
    multipart:
      max-request-size: 35MB  # 上传文件的总大小限制
      max-file-size: 10MB      # 单个文件的大小限制

#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: Asia/Shanghai



mybatis-plus:
  configuration:
    #mp日志输出
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      table-prefix: ms_


qiniu:
  accessKey: 1srsgnuP1JJ8Ukrag_R_ekgKqpHhuPgBlsn9Wfcs
  accessSecretKey: AdlhkeNmNmbzKKA72HwoAHP__b6VFSHCE8_h2H_5
  bucketName: lignting